repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-vcs-permalinks
    -   id: check-json
    -   id: check-ast
    -   id: pretty-format-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
        args: [--pytest-test-first]
    -   id: fix-encoding-pragma
    -   id: detect-private-key
    -   id: debug-statements
- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.0
  hooks:
    - id: docformatter
      args: [--in-place, --wrap-summaries=120, --wrap-descriptions=120]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/pylint
    rev: v2.15.6
    hooks:
    -   id: pylint
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        entry: isort --profile=black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--follow-imports=silent, --ignore-missing-imports,  --allow-redefinition]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        additional_dependencies: ["toml"]
